In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [2]:
df = pd.read_csv("house_prices.csv")
df

Area   Price
0   600  150000
1   900  200000
2  1100  250000
3  1300  275000
4  1600  320000

In [3]:
x = df[['Area']]
y = df['Price']

In [4]:
model = linear_model.LinearRegression()
model.fit(x,y)

LinearRegression()

In [5]:
model.coef_

array([172.4137931])

In [6]:
model.intercept_

np.float64(49344.82758620696)

In [7]:
model.predict(pd.DataFrame({'Area' : [5000] }))

array([911413.79310345])

#### Saving the model in a file using the pickle module

#### Import pickle module 

In [8]:
import pickle

In [9]:
# Open a file named 'model_pickle' in write-binary mode
with open('model_pickle', 'wb') as f:
    # Serialize and save the trained model to the file
    pickle.dump(model, f)

#### Load the trained model using pickle
#### The following code opens the file named 'model_pickle' in read-binary mode and loads the serialized model using the `pickle` module. This allows us to use the trained model for making predictions or further analysis.

In [10]:
with open('model_pickle','rb') as f:
    mp = pickle.load(f)

#### Now the required data can be predicted

In [11]:
mp.predict(pd.DataFrame({'Area' : [5000]}))

array([911413.79310345])

#### Saving the model using joblib


In [12]:
import joblib

In [13]:
# Save the trained model to a file named 'model_joblib'
# This allows us to efficiently serialize and store the model for later use
joblib.dump(model, 'model_joblib')

['model_joblib']

#### Load the trained model using joblib
#### The following code loads the serialized model from the file named 'model_joblib' using the `joblib` module. This allows us to use the trained model for making predictions or further analysis.

In [14]:
mj = joblib.load('model_joblib')

#### Predicting the price for an area of 5000 using the loaded model `mj`

In [15]:
mj.predict(pd.DataFrame({'Area' : [5000]}))

array([911413.79310345])