## NUMPY

In [1]:
import numpy as np

In [2]:
myarr = np.array([2,3,45])

In [3]:
myarr

array([ 2,  3, 45])

In [4]:
myarr.dtype

dtype('int64')

In [5]:
myarr2 = np.array([[2,3,4,5]])

In [6]:
myarr2[0,2]

np.int64(4)

In [7]:
myarr2.shape

(1, 4)

## Array creation : Conversion from other python structures

In [8]:
listarray = np.array([[1,2,3] , [44,5,6] , [66,75,9]])

In [9]:
listarray

array([[ 1,  2,  3],
       [44,  5,  6],
       [66, 75,  9]])

In [10]:
listarray.size

9

In [11]:
listarray.shape

(3, 3)

In [12]:
listarray.dtype

dtype('int64')

In [13]:
np.array({23,43,5})

array({43, 5, 23}, dtype=object)

## Intrinsic Numpy array creation

In [14]:
zeros = np.zeros((2,5))

In [15]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
rng = np.arange(20)

In [17]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
lspace = np.linspace(1,5,4)

In [19]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [21]:
emp = np.empty((4,6))

In [22]:
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        6.23058707e-307, 8.90105597e-307, 6.23053614e-307],
       [7.56592338e-307, 1.60220528e-306, 7.56602523e-307,
        1.42417221e-306, 1.37961641e-306, 2.22522597e-306],
       [1.33511969e-306, 6.23037657e-307, 6.23053954e-307,
        9.34609790e-307, 8.45593934e-307, 9.34600963e-307],
       [1.86921143e-306, 6.23061763e-307, 1.60220393e-306,
        1.86921007e-306, 7.56596412e-307, 2.22520559e-306]])

In [23]:
ide = np.identity(45)

In [24]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [25]:
arr = np.arange(99)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [27]:
arr = arr.reshape(3,33)

In [28]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [29]:
arr = arr.ravel()

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [31]:
arr.shape

(99,)

In [32]:
x = [[1,2,3] , [5,3,6] , [7,8,5]]

In [33]:
arr = np.array(x)

In [34]:
arr

array([[1, 2, 3],
       [5, 3, 6],
       [7, 8, 5]])

In [36]:
arr.sum(axis=0)

array([13, 13, 14])

In [55]:
arr.argmax(axis = 0)

array([2, 2, 1])

In [53]:
arr.argsort()

array([[0, 1, 2],
       [1, 0, 2],
       [2, 0, 1]])

In [37]:
arr.sum(axis = 1)

array([ 6, 14, 20])

In [54]:
arr.argmax()

np.int64(7)

In [38]:
arr.T

array([[1, 5, 7],
       [2, 3, 8],
       [3, 6, 5]])

In [56]:
arr.ravel()

array([1, 2, 3, 5, 3, 6, 7, 8, 5])

In [57]:
arr.reshape(3,3)

array([[1, 2, 3],
       [5, 3, 6],
       [7, 8, 5]])

In [39]:
arr.flat

In [ ]:
for item in arr.flat:
    print(item)

1
2
3
5
3
6
7
8
5


# Hello

In [45]:
arr.ndim

2

In [46]:
arr.nbytes

72

In [48]:
one =np.array([1,44,5,445])

In [49]:
one

array([  1,  44,   5, 445])

In [50]:
one.argmax()

np.int64(3)

In [51]:
one.argmin()

np.int64(0)

In [52]:
one.argsort()

array([0, 2, 1, 3])

In [58]:
arr

array([[1, 2, 3],
       [5, 3, 6],
       [7, 8, 5]])

In [59]:
arr2 = np.array([[1, 7, 3],
       [5, 9, 2],
       [4, 8, 3]])

In [60]:
arr + arr2

array([[ 2,  9,  6],
       [10, 12,  8],
       [11, 16,  8]])

In [61]:
arr - arr2

array([[ 0, -5,  0],
       [ 0, -6,  4],
       [ 3,  0,  2]])

In [62]:
arr * arr2

array([[ 1, 14,  9],
       [25, 27, 12],
       [28, 64, 15]])

In [63]:
arr / arr2

array([[1.        , 0.28571429, 1.        ],
       [1.        , 0.33333333, 3.        ],
       [1.75      , 1.        , 1.66666667]])

In [64]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.23606798, 1.73205081, 2.44948974],
       [2.64575131, 2.82842712, 2.23606798]])

In [65]:
arr

array([[1, 2, 3],
       [5, 3, 6],
       [7, 8, 5]])

In [66]:
arr.sum()

np.int64(40)

In [67]:
arr.max()

np.int64(8)

In [73]:
np.where(arr>6)

(array([2, 2]), array([0, 1]))

In [69]:
arr

array([[1, 2, 3],
       [5, 3, 6],
       [7, 8, 5]])

In [70]:
np.where(arr > 5)

(array([1, 2, 2]), array([2, 0, 1]))

In [74]:
import sys

In [75]:
py_ar = [2,44,3,5]

In [76]:
np_ar = np.array(py_ar)

In [77]:
sys.getsizeof(1) * len(py_ar)

112

In [ ]:
np_ar.itemsize * np_ar.size

32

In [1]:
print("hey")

hey


In [2]:
4+5

9